#!/bin/sh

PIDFILE="`dirname $0`/shellinaboxd.pid"

shellinaboxd \
	--localhost-only \
	--no-beep \
	--disable-ssl \
	--port=4101 \
	--css=css/shellinabox.css \

echo "shellinaboxd started, pid `cat $PIDFILE`"
